Explicit support for django

diff --git a/bin/steps/collectstatic b/bin/steps/collectstatic
--- a/bin/steps/collectstatic
+++ b/bin/steps/collectstatic
@@ -7,7 +7,6 @@
 # This functionality will only activate if Django is in requirements.txt.
 
 # Runtime arguments:
-#   - $DISABLE_COLLECTSTATIC: disables this functionality.
 #   - $DEBUG_COLLECTSTATIC: upon failure, print out environment variables.
 
 source $BIN_DIR/utils
@@ -16,54 +15,15 @@ source $BIN_DIR/utils
 MANAGE_FILE=$(find . -maxdepth 3 -type f -name 'manage.py' -printf '%d\t%P\n' | sort -nk1 | cut -f2 | head -1)
 MANAGE_FILE=${MANAGE_FILE:-fakepath}
 
-# Legacy file-based support for $DISABLE_COLLECTSTATIC
-[ -f .heroku/collectstatic_disabled ] && DISABLE_COLLECTSTATIC=1
 
-# Ensure that Django is explicitly specified in requirements.txt
-pip-grep -s requirements.txt django Django && DJANGO_INSTALLED=1
+set +e
+puts-cmd "python $MANAGE_FILE migrate"
+python $MANAGE_FILE migrate
+puts-cmd "python $MANAGE_FILE seed_db"
+python $MANAGE_FILE seed_db
+puts-cmd "python $MANAGE_FILE collectstatic --noinput"
+# Run collectstatic, cleanup some of the noisy output.
+python $MANAGE_FILE collectstatic --noinput --traceback 2>&1 | sed '/^Post-processed/d;/^Copying/d;/^$/d' | indent
+COLLECTSTATIC_STATUS="${PIPESTATUS[0]}"
 
-bpwatch start collectstatic  # metrics collection
-
-if [ ! "$DISABLE_COLLECTSTATIC" ] && [ -f "$MANAGE_FILE" ] && [ "$DJANGO_INSTALLED" ]; then
-    set +e
-    puts-cmd "python $MANAGE_FILE migrate"
-    python $MANAGE_FILE migrate
-    puts-cmd "python $MANAGE_FILE seed_db"
-    python $MANAGE_FILE seed_db
-    puts-cmd "python $MANAGE_FILE collectstatic --noinput"
-    # Run collectstatic, cleanup some of the noisy output.
-    python $MANAGE_FILE collectstatic --noinput --traceback 2>&1 | sed '/^Post-processed/d;/^Copying/d;/^$/d' | indent
-    COLLECTSTATIC_STATUS="${PIPESTATUS[0]}"
-
-    set -e
-
-    # Display a warning if collectstatic failed.
-    [ $COLLECTSTATIC_STATUS -ne 0 ] && {
-
-        echo
-        echo " !     Error while running '$ python $MANAGE_FILE collectstatic --noinput'."
-        echo "       See traceback above for details."
-        echo
-        echo "       You may need to update application code to resolve this error."
-        echo "       Or, you can disable collectstatic for this application:"
-        echo
-        echo "          $ heroku config:set DISABLE_COLLECTSTATIC=1"
-        echo
-        echo "       https://devcenter.heroku.com/articles/django-assets"
-
-        # Additionally, dump out the environment, if debug mode is on.
-        if [ "$DEBUG_COLLECTSTATIC" ]; then
-            echo
-            echo "****** Collectstatic environment variables:"
-            echo
-            env | indent
-        fi
-
-        # Abort the build.
-        exit 1
-    }
-
-    echo
-fi
-
-bpwatch stop collectstatic  # metrics collection
+set -e
